[package]
name = "wasm_example"
version = "0.1.0"
authors = ["David Pojunas <davidapojunas@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.51"
sophia = "0.3.0"