/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbg_foo_free(a: number): void;
export function foo_new(a: number): number;
export function foo_get(a: number): number;
export function foo_set(a: number, b: number): void;
export function foo_display(a: number): void;
export function run_alert(a: number, b: number): void;
export function load_graph(a: number, b: number): void;
export function __wbg_jsterm_free(a: number): void;
export function jsterm_new(a: number, b: number): number;
export function jsterm_n3(a: number, b: number): void;
export function __wbg_jsquad_free(a: number): void;
export function jsquad_s(a: number): number;
export function __wbg_jsdataset_free(a: number): void;
export function jsdataset_new(): number;
export function jsdataset_load(a: number, b: number, c: number): number;
export function jsdataset_first_subject(a: number): number;
export function jsdataset_quads(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
